version: 2
orbs:
  jira: circleci/jira@2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.21.5
    
    working_directory: go/src/github.com/PkMs7/api-session-finance-dio
    steps:
      - checkout

      - run: go version
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - jira/notify:
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
workflows:
  build-workflow:
    jobs:
      - build:
          context: JIRA_WEBHOOK_URL